<!DOCTYPE html>
<html>
<body>

<h2>JavaScript Error Handling</h2>

<p>How to use <b>catch</b> to display an error.</p>

<p id="demo"></p>
<p id="demo1"></p>
<p id="demo2"></p>
<p id="demo3"></p>
<p id="demo4"></p>
<p id="demo5"></p>
<p id="demo6"></p>

<script>
try {
  adddlert("Welcome guest!");
}
catch(err) {
  document.getElementById("demo").innerHTML = err.message;
}

let num = 1;
try {
  num.toPrecision(500);
}
catch(err) {
  document.getElementById("demo1").innerHTML = err.name;
}
let x = 5;
try {
  x = y + 1;
}
catch(err) {
  document.getElementById("demo2").innerHTML = err.name;
}
try {
  eval("'Hello");
}
catch(err) {
  document.getElementById("demo3").innerHTML = err.name;
}


try {
  num.toUpperCase();
}
catch(err) {
  document.getElementById("demo4").innerHTML = err.name;
}

try {
  decodeURI("http://www.google.com");
}
catch(err) {
  document.getElementById("demo5").innerHTML = err.name;
}finally {
    document.getElementById("demo6").innerHTML = "Finally any ways";
  }
</script>

</body>
</html>


<!-- EvalError	Deprecated - use SyntaxError instead	 
RangeError	A number "out of range" has occurred	
ReferenceError	An illegal reference has occurred	
SyntaxError	A syntax error has occurred	
TypeError	A type error has occurred	
URIError	An error in encodeURI() has occurred -->